Upgrading Yew 0.19->0.21
titanclass/yew-chart pull request #49
Opened 2023-11-18 10:07 UTC by Enigo

Hey there!
Wanted to give it a try in my project, but I'm already on 0.21, so I thought maybe you can consider updating as well.

I tried both example projects and also `cargo test` - everything seems to be working fine.
In case you are having compilation issues make sure to check https://github.com/yewstack/yew/issues/3366 out.
And also updated other dependencies.

2023-11-19 04:02 UTC, huntc requested changes
Thanks for the PR. Small changes required...

2023-11-19 04:02 UTC, huntc commented on examples/scatter/src/main.rs
> +                    horizontal_scale_step={None}
Instead of this, please declare the property to default i.e.:

```rust
    #[prop_or_default]
    pub horizontal_scale_step: Option<A>,
```

2023-11-19 04:02 UTC, huntc commented on examples/scatter/src/main.rs
> +                    tooltipper={None}
As above

2023-11-19 04:02 UTC, huntc commented on src/axis.rs
For https://github.com/titanclass/yew-chart/pull/49/files#diff-53b70792e1a11caa17fd6f27781f2cc6cf6aa6482f22ee7deb8ef87727e69179L85

```rust
    #[prop_or_default]
    pub title: Option<String>,
```

2023-11-19 08:40 UTC, Enigo commented on examples/scatter/src/main.rs
> +                    horizontal_scale_step={None}
done

2023-11-19 08:40 UTC, Enigo commented on examples/scatter/src/main.rs
> +                    tooltipper={None}
done

2023-11-19 08:41 UTC, Enigo commented on src/axis.rs
unsure what to fix here exactly?

2023-11-19 09:26 UTC, huntc commented on src/axis.rs
Ah sorry. The option in the props also needs the same treatment. Thanks.

2023-11-19 13:30 UTC, Enigo commented on src/axis.rs
ah, I see
done

2023-11-19 18:37 UTC, huntc approved these changes
Thank you so much! Awesome.

2023-11-19 20:22 UTC, merged

2023-11-20 03:03 UTC, huntc commented
Released as 0.6.0. https://crates.io/crates/yew-chart/0.6.0